# Generated by Django 4.2 on 2023-05-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
    ]
