# Generated by Django 4.2 on 2023-05-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_pannel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
