# Generated by Django 4.2 on 2023-05-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_pannel', '0004_book_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_table',
            name='user_phone',
            field=models.CharField(max_length=20),
        ),
    ]
