# Generated by Django 4.2 on 2023-05-22 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_pannel', '0005_alter_book_table_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('user_email', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=230)),
            ],
        ),
    ]
