# Generated by Django 4.2 on 2023-05-23 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_pannel', '0006_contact_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=20)),
                ('subscribed', models.CharField(max_length=5)),
            ],
        ),
    ]
